spring.application.name=arcgarden

# Credenciais
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
spring.datasource.username=RM574069
spring.datasource.password=210208

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
